"""Add Employee model and change location to address

Revision ID: 05a274f27397
Revises: 7204c3fcbcf5
Create Date: 2025-06-14 18:35:30.917586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a274f27397'
down_revision = '7204c3fcbcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.VARCHAR(), nullable=False))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###
